feat: waiting room user journey ref: WSC-1011
zextras/carbonio-ws-collaboration-ui pull request #228
Opened 2024-02-08 10:38 UTC by lisaparma

2024-02-23 10:55 UTC, yukiLu6 approved these changes, later dismissed

2024-02-23 11:18 UTC, CerDennis commented on src/store/slices/MeetingsStoreSlice.test.ts
> +			expect(size(waitingList)).toBe(2);
Here check also the values are the new ones

2024-02-23 11:25 UTC, CerDennis commented
![image](https://github.com/zextras/carbonio-ws-collaboration-ui/assets/31632342/d5580d6d-c325-4adc-8f74-0ab88d2f12e3)

User without conversations can't see the button to create scheduled rooms

2024-02-23 11:26 UTC, CerDennis requested changes
image
User without conversations can't see the button to create scheduled rooms

2024-02-23 11:32 UTC, CerDennis commented
Waiting room media devices toggles are not working

https://github.com/zextras/carbonio-ws-collaboration-ui/assets/31632342/017a764c-d31d-437e-9030-0d1be6495cef

2024-02-23 11:38 UTC, CerDennis commented
![image](https://github.com/zextras/carbonio-ws-collaboration-ui/assets/31632342/9c008529-859e-456d-8577-7fa240292a27)
 I entered the waiting room with another user in another browser and in the wsc view of the moderator I see the snackbar that tells me someone is waiting to enter but I don't now in which room

2024-02-23 13:10 UTC, CerDennis commented
> ![image](https://private-user-images.githubusercontent.com/31632342/307308070-9c008529-859e-456d-8577-7fa240292a27.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg2ODg1OTEsIm5iZiI6MTcwODY4ODI5MSwicGF0aCI6Ii8zMTYzMjM0Mi8zMDczMDgwNzAtOWMwMDg1MjktODU5ZS00NTZkLTg1NzctN2ZhMjQwMjkyYTI3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjIzVDExMzgxMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRmODQyY2ZjN2VmOWJkNzYyY2YxOWRiYjNlMzg2ZDA5NmUyY2FiMThmNmIyNmY2YWQwNGM4ODBhY2U0MjZkYzQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.5FCTFONflZKFjYxCGITPRp2q0GNszDmMmurhaGlUJfc) I entered the waiting room with another user in another browser and in the wsc view of the moderator I see the snackbar that tells me someone is waiting to enter but I don't now in which room

For this one we can discuss further on with @AliceTincani if we can find an improvement

2024-02-23 13:14 UTC, CerDennis commented
After reload of page I can't see the waiting list
- as moderator I enter the virtual room
- an user require to enter the meeting by the waiting room
- I receive the notification
- I leave the meeting
- I enter the meeting again
I expect to see the waiting list with the user inside but I don't see anything

2024-02-23 13:48 UTC, CerDennis commented on src/meetings/views/AccessMeetingPageView.tsx
> +			{hasUserDirectAccess === false && (
Here if it's undefined we are not covering the case

2024-02-23 13:49 UTC, CerDennis commented on src/meetings/views/InfoPage.tsx
> +			centralLabel = t('', 'The meeting you are looking for does not exist');
Are missing keys on porpuse

2024-02-23 15:33 UTC, lisaparma commented
>  User without conversations can't see the button to create scheduled rooms

https://zextras.atlassian.net/browse/WSC-1250

2024-02-23 15:39 UTC, lisaparma commented
> After reload of page I can't see the waiting list
> 
> * as moderator I enter the virtual room
> * an user require to enter the meeting by the waiting room
> * I receive the notification
> * I leave the meeting
> * I enter the meeting again
>   I expect to see the waiting list with the user inside but I don't see anything

https://zextras.atlassian.net/browse/WSC-1304

2024-02-26 11:27 UTC, CerDennis submitted a review, later dismissed

2024-02-26 11:27 UTC, yukiLu6 submitted a review, later dismissed

2024-02-27 14:17 UTC, yukiLu6 approved these changes

2024-02-27 14:26 UTC, CerDennis approved these changes

2024-02-27 14:27 UTC, merged