feat: new is typing implementation refs: WSC-1329
zextras/carbonio-ws-collaboration-ui pull request #255
Opened 2024-03-18 11:32 UTC by yukiLu6

2024-03-22 11:29 UTC, CerDennis requested changes
Running tests I see some warnings for update states due to timout usages, please fix them

![image](https://github.com/zextras/carbonio-ws-collaboration-ui/assets/31632342/e4abbc9e-cc86-467c-905e-97a6ef9d98e4)

2024-03-22 11:33 UTC, CerDennis commented on src/chats/components/conversation/ConversationHeader.test.tsx
> +		const isWriting = await screen.findByText(/Roberto and 3 others are typing.../i);
Here you are harcoding the name of the user, extract it from the mock object

2024-03-22 11:33 UTC, CerDennis commented on src/chats/components/conversation/ConversationHeader.test.tsx
> +			store.setLoginInfo(mockPaoloUser.id, 'Paolo');
Here you are harcoding the name of the user, extract it from the mock object

2024-03-22 11:33 UTC, CerDennis commented on src/chats/components/conversation/ConversationHeader.test.tsx
> +			store.setLoginInfo(mockPaoloUser.id, 'Paolo');
Here you are harcoding the name of the user, extract it from the mock object

2024-03-22 11:34 UTC, CerDennis commented on src/chats/components/conversation/ConversationHeader.test.tsx
>  		expect(screen.queryByTestId('ConversationHeaderMeetingButton')).not.toBeInTheDocument();
Split the tests for the is writing function in a separte suite so it's cleaner

2024-03-22 13:29 UTC, CerDennis commented on src/meetings/components/sidebar/MeetingConversationAccordion/MeetingConversationAccordion.tsx
Here we could also split in a new component the iswriting managment make it more atomic

2024-03-22 13:35 UTC, CerDennis commented on src/hooks/useIsWritingLabel.tsx
> +	if (writingListNames === undefined || writingListNames?.length === 0) return undefined;
please add an aempty line at the end of a statement :'(

2024-03-26 11:03 UTC, lisaparma commented
If the last message is a configuration message, when the "is typing" label appears there is a small change in height

https://github.com/zextras/carbonio-ws-collaboration-ui/assets/30258876/1c1eb20d-8245-4f81-bc3d-7fcf35ade660

2024-03-26 11:03 UTC, lisaparma requested changes

2024-03-26 11:03 UTC, lisaparma commented on src/chats/components/conversation/ConversationHeader.tsx
> +					{
`{` and `}` are useless if there isn't a condition

2024-03-26 11:03 UTC, lisaparma commented on src/meetings/components/sidebar/MeetingConversationAccordion/MeetingChatAccordionTitle.tsx
> +			{
`{` and `}` are useless if there isn't a condition

2024-03-26 13:03 UTC, lisaparma approved these changes

2024-03-26 13:10 UTC, CerDennis approved these changes

2024-03-26 13:12 UTC, merged