fix: highlight color on meeting ref: WSC-1368
zextras/carbonio-ws-collaboration-ui pull request #291
Opened 2024-04-30 12:18 UTC by lisaparma

2024-05-02 15:18 UTC, CerDennis requested changes
If I have the darkreader disabled in the settings, in the chat in lightmode I'don't see the effect when click on a replayed message

2024-05-03 07:17 UTC, CerDennis approved these changes, later dismissed

2024-05-03 10:17 UTC, yukiLu6 approved these changes

2024-05-06 07:09 UTC, CerDennis approved these changes

2024-05-06 07:15 UTC, merged