feat: let the user export chats ref: WSC-1456
zextras/carbonio-ws-collaboration-ui pull request #334
Opened 2024-06-25 14:47 UTC by lisaparma

2024-06-26 13:41 UTC, CerDennis requested changes

2024-06-26 13:41 UTC, CerDennis commented on src/network/xmpp/handlers/historyMessageHandler.ts
> +	if (chatExporting && chatExporting.roomId === roomId) {
you can simplify with if (chatExporting?.roomId === roomId)

if (chatExporting?.roomId === roomId) {
		const isHistoryComplete = !!getRequiredTagElement(stanza, 'fin').getAttribute('complete');
		chatExporting.exporter.handleFullHistoryResponse(isHistoryComplete);
}

2024-06-26 14:30 UTC, CerDennis approved these changes, later dismissed

2024-06-27 13:28 UTC, yukiLu6 approved these changes

2024-06-27 13:31 UTC, merged