refactor: update CDS to 6.0.1 ref: WSC-1433
zextras/carbonio-ws-collaboration-ui pull request #340
Opened 2024-06-28 08:54 UTC by lisaparma

2024-07-01 10:30 UTC, CerDennis requested changes

2024-07-01 10:30 UTC, CerDennis commented on src/chats/components/conversation/forwardModal/ForwardMessageModal.tsx
https://github.com/zextras/carbonio-ws-collaboration-ui/assets/31632342/093efa97-ad1e-4857-b7c3-a5148bfbdfba

Forward modal is broken

2024-07-01 10:30 UTC, CerDennis commented on src/meetings/components/sidebar/recordingAccordion/StopRecordingModal.tsx
The stop recording button is now primary while it should be red

![Screenshot 2024-07-01 alle 12 09 27](https://github.com/zextras/carbonio-ws-collaboration-ui/assets/31632342/04e76916-2013-47dc-a234-56125d0bfea4)

2024-07-02 14:38 UTC, CerDennis approved these changes

2024-07-02 15:28 UTC, yukiLu6 approved these changes

2024-07-03 09:29 UTC, merged