feat: virtual background: blur refs: WSC-1259
zextras/carbonio-ws-collaboration-ui pull request #347
Opened 2024-07-03 13:32 UTC by yukiLu6

2024-07-08 09:40 UTC, CerDennis requested changes
If I change video source while blur is active, the blur effect doesn't persist and others can see my background

2024-07-08 09:44 UTC, CerDennis requested changes
<img width="346" alt="Screenshot 2024-07-08 alle 11 42 39" src="https://github.com/zextras/carbonio-ws-collaboration-ui/assets/31632342/48f5190d-0c0f-4c17-a01c-09b751326189">
<img width="343" alt="Screenshot 2024-07-08 alle 11 42 49" src="https://github.com/zextras/carbonio-ws-collaboration-ui/assets/31632342/f145188b-b939-4160-b3a5-c691027d2d13">

On firefox the actual image ratio is different when the blur effect is added

2024-07-08 16:04 UTC, CerDennis commented on src/meetings/components/meetingActionsBar/CameraButton.tsx
> +				customComponent: <Text weight="bold">Video effect</Text>
Missing translation

2024-07-08 16:05 UTC, CerDennis commented on src/meetings/components/meetingActionsBar/CameraButton.tsx
> +	const blur = useStore((store) => getIsBackgroundBlurred(store, meetingId));
change it to isBlur to be better intuitive

2024-07-09 09:05 UTC, lisaparma approved these changes

2024-07-09 14:31 UTC, CerDennis approved these changes

2024-07-09 14:53 UTC, merged