style: change format of forward info
zextras/carbonio-ws-collaboration-ui pull request #396
Opened 2024-09-16 09:39 UTC by CerDennis

Remove bold style from text refs: WSC-1519

2024-09-17 12:38 UTC, lisaparma requested changes

2024-09-17 12:38 UTC, lisaparma commented on src/chats/components/conversation/messageBubbles/ForwardInfo.tsx
> +			i18nKey="gsdf"
use the real key

2024-09-18 15:30 UTC, yukiLu6 approved these changes

2024-09-19 09:43 UTC, lisaparma approved these changes

2024-09-19 13:02 UTC, merged