fix: fixes for update refs: WSC-1592
zextras/carbonio-ws-collaboration-ui pull request #397
Opened 2024-09-16 12:06 UTC by yukiLu6

Before opening this pr we need to:

- [ ] delete .tgz files
- [ ] update DS, Preview and Shell version with the ones in which react18 is used
- [ ] fix the tests that are not working due to these updates

2024-10-03 09:48 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/zextras/carbonio-ws-collaboration-ui?pullRequest=397) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/zextras/carbonio-ws-collaboration-ui?pullRequest=397) before we can accept your contribution.<br/><hr/>**Lucrezia** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/zextras/carbonio-ws-collaboration-ui?pullRequest=397) it.</sub>

2024-10-03 09:56 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/zextras/carbonio-ws-collaboration-ui?pullRequest=397) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/zextras/carbonio-ws-collaboration-ui?pullRequest=397) before we can accept your contribution.<br/>**1** out of **2** committers have signed the CLA.<br/><br/>:white_check_mark: yukiLu6<br/>:x: Lucrezia<br/><hr/>**Lucrezia** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/zextras/carbonio-ws-collaboration-ui?pullRequest=397) it.</sub>

2024-10-09 09:59 UTC, lisaparma submitted a review, later dismissed

2024-10-09 10:03 UTC, CerDennis requested changes

2024-10-09 10:03 UTC, CerDennis commented on src/chats/components/infoPanel/conversationActionsAccordion/MuteConversationAction.test.tsx
> +	// test('undo mute', async () => {
Here better to leave a TODO so we know here we have to fix the missing tests

2024-10-09 10:03 UTC, CerDennis commented on src/chats/components/secondaryBar/SecondaryBarView.test.tsx
> +	// describe('FilteredGal inside SecondaryBarView tests', () => {
Same TODO here

2024-10-09 10:03 UTC, CerDennis commented on src/meetings/components/meetingAccessPoint/useAccessMeetingInformation.test.tsx
> +	// test('Internal user has not userHasDirectAccess to scheduled meeting', async () => {
same TODO

2024-10-09 10:34 UTC, CerDennis approved these changes

2024-10-09 10:38 UTC, lisaparma approved these changes

2024-10-09 10:43 UTC, merged