feat: add moderator while creating virtual room
zextras/carbonio-ws-collaboration-ui pull request #435
Opened 2024-11-22 17:03 UTC by CerDennis

user will be now able to add moderators while creating the virtual room

refs: WSC-1752

2024-11-27 11:16 UTC, lisaparma requested changes

2024-11-27 11:16 UTC, lisaparma commented on src/chats/components/RegisterVirtualRoomCreationButton.tsx
> + * SPDX-FileCopyrightText: 2022 Zextras <https://www.zextras.com>
2024

2024-11-27 11:16 UTC, lisaparma commented on src/chats/components/secondaryBar/virtualRoomWidget/CreateVirtualRoomButton.tsx
This component has become very simple, without state or other particular things but only with props.
I think it's better to simplify the structure by using `Button` and `CreateVirtualRoomModal` directly in the `VirtualRoomList.tsx` file, without creating another component just to pass props.

2024-11-27 11:16 UTC, lisaparma commented on src/chats/components/secondaryBar/virtualRoomWidget/ModeratorsContactsSelection.tsx
> +import { Spinner } from '@zextras/carbonio-shell-ui';
Don't use Shell's Spinner

2024-11-28 09:38 UTC, lisaparma approved these changes

2024-11-28 10:14 UTC, yukiLu6 approved these changes

2024-11-28 13:26 UTC, merged