fix: sender name visible when previous message is a deleted message
zextras/carbonio-ws-collaboration-ui pull request #438
Opened 2024-11-27 13:38 UTC by CerDennis

Refs: WSC-1766

2024-11-28 09:35 UTC, lisaparma requested changes

2024-11-28 09:35 UTC, lisaparma commented on src/chats/components/conversation/messageBubbles/Bubble.tsx
> +		(!prevMessageIsFromSameSender || (prevMessageIsFromSameSender && isPrevMessageDeleted));
This logic expression can be simplified in `(!prevMessageIsFromSameSender || isPrevMessageDeleted)` because if we enter the second condition, `prevMessageIsFromSameSender` is surely true

2024-11-28 09:35 UTC, lisaparma commented on src/chats/components/conversation/messageBubbles/Bubble.tsx
> +	isPrevMessageDeleted: boolean;
I think that It would be better if isPrevMessageDeleted was optional with false as default value and not mandatory, since it’s only needed for a specific case

2024-11-28 13:31 UTC, lisaparma approved these changes

2024-11-29 16:32 UTC, yukiLu6 approved these changes

2024-11-29 17:26 UTC, merged